services:
  modelserving:
    image: modelserving:latest
    container_name: modelserving
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 1234
    volumes:
      - .:/home/modelserving/
    working_dir: /home/modelserving
    ports:
      - 1234:1234